### ISSUE TITLE
Error when running app on Xcode 7.1

### ISSUE THREAD

**Issue by johnduke99** [wrld3d/ios-api-example#1]
Hello,

Just wanted to report that I am receiving his error when running on Xcode 7.1 as soon as App starts. App works ok if I switch to apple maps or google maps as soon as app start. But switching back to eegeo results in this again.

2016-01-16 21:16:02.366 eeGeoApiExampleApp[853:20622] V.0.0.0(1)
2016-01-16 21:16:05.925 eeGeoApiExampleApp[853:20622] Eegeo ASSERT: /buildAgent/work/d7fbe78406a06eb1/platform/Rendering/AsyncTexturing/HttpAsyncTextureLoader.cpp (202) Invalid placeholder texture set

**Comment by Fahad123321** [comment]
I too have the same issue, can anyone rescue? 
![eegeo-error](https://cloud.githubusercontent.com/assets/4937733/12378452/bc93c0c2-bd5f-11e5-8951-e0f4260dfd74.png)

Printing description of updateParameters:
(Eegeo::EegeoUpdateParameters) updateParameters = {
  m_frameDeltaSeconds = 0.0364359617
  m_ecefLocation = (x = 4257084.5292788921, y = 3908383.159914101, z = -2701487.4104555962)
  m_ecefInterestPoint = (x = 4255592.6381656108, y = 3908606.5806904682, z = -2700540.676813018)
  m_viewMatrix = {
    m_rows = {
      [0] = (x = 0.535806954, y = 0.105919831, z = -0.837670565, w = 0)
      [1] = (x = 0.0000000037252903, y = 0.992100358, z = 0.125446826, w = 0)
      [2] = (x = 0.844340563, y = -0.0672152713, z = 0.531574249, w = 0)
      [3] = (x = -0, y = -0, z = -0, w = 1)
    }
  }
  m_projectionMatrix = {
    m_rows = {
      [0] = (x = 3.80523682, y = 0, z = 0, w = 0)
      [1] = (x = 0, y = 2.55270791, z = 0, w = 0)
      [2] = (x = 0, y = 0, z = 1.5, w = 1)
      [3] = (x = 0, y = 0, z = -1577.72693, w = 0)
    }
  }
  m_viewProjectionMatrix = {
    m_rows = {
      [0] = (x = 2.03887224, y = 0.270382375, z = -1.25650585, w = -0.837670565)
      [1] = (x = 0.0000000141756118, y = 2.53254247, z = 0.188170239, w = 0.125446826)
      [2] = (x = 3.2129159, y = -0.171580955, z = 0.797361374, w = 0.531574249)
      [3] = (x = 0, y = 0, z = -1577.72693, w = 0)
    }
  }
  m_streamingVolume = 0x00007ff298ca3e30
  m_screenProperties = {
    m_screenWidth = 750
    m_screenHeight = 1118
    m_screenPixelScale = 2
    m_screenDpi = 264
  }
}

**Comment by scottmurray** [comment]
Thank you johnduke99 and FahadReveApp for reporting this issue. The problem was caused by the incorrect embedding of texture resources in the Xcode project file, and should now be fixed in latest master. We intend to better automate the generation of projects to mitigate problems like this in future.

**Comment by shahab-interface** [comment]
Is it resolved ? @scottmurray  I am still getting this error. Can you please update ?
